### ISSUE TITLE
移植到win10、vs2019 c++上，误检率有点高

### ISSUE THREAD

**Issue by duoduo888999** [FeiGeChuanShu/ncnn-Android-mediapipe_hand#10]
你好，在android上检测都很流畅，
我把模型和代码都移植到了windows上，win10、vs2019 c++，用摄像头去实时检测，帧率还可以，
但很多时候能检测到手掌，但是检测不到拳头，误检率也有点高。
（android和windows上视频分辨率都是640*480）
请问是模型的原因，还是移植到windows上有的代码需要修改，或者是其他什么原因？
能给点思路和建议吗

**Comment by duoduo888999** [comment]
找到原因了，是我代码的问题

**Comment by westpilgrim63** [comment]
https://github.com/FeiGeChuanShu/ncnn_nanodet_hand/issues/13
你好！你移植的hand pose有问题吗？我的hand pose都缩成一团了。我看这两个项目用到的手部姿态模型是同一个

**Comment by westpilgrim63** [comment]
我是win11,vs2022

**Comment by duoduo888999** [comment]
没遇到过这种情况，可能与你的windows和vs的版本有关。
关键点的坐标可以输出，你逐步打印看看哪里出错了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年9月7日(周四) 下午3:07
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [FeiGeChuanShu/ncnn-Android-mediapipe_hand] 移植到win10、vs2019 c++上，误检率有点高 (Issue #10)




 
我是win11,vs2022

**Comment by westpilgrim63** [comment]
OK

**Comment by westpilgrim63** [comment]
解决了，只要把NCNN的版本替换成20210720的版本就可以了
