### ISSUE TITLE
大佬，我想请教下可以获得z的坐标吗

### ISSUE THREAD

**Issue by juneweng** [FeiGeChuanShu/ncnn-Android-mediapipe_hand#8]

**Comment by Stephenfang51** [comment]
@juneweng  请问解决了吗

**Comment by shirok1** [comment]
同问

**Comment by juneweng** [comment]
@Stephenfang51 @shirok1 用realsense采集的深度

**Comment by shirok1** [comment]
实际上推理出的坐标跟原始的模型一样，依然是有深度的，在 `LandmarkDetect::detect` 里 `points_data[i * 3 + 2]` 就是 z 坐标……

**Comment by juneweng** [comment]
@shirok1 感谢感谢，我去试试

**Comment by juneweng** [comment]
@shirok1 我试了一下，值全是0呀，xy到小数点后三位，您知道怎么解决吗
